what-is-a-thing:
    heading: "What is a thing?"
    summary: "On constraints, meaning, and what learning algorithms might be missing."
    date: "10/01/2026"
    careless-wonder: true
    draft: true

update-rules:
    heading: "Update Rules"
    summary: "On architectures of learning systems, and their dynamics."
    date: "14/01/2026"
    careless-wonder: true
    draft: true

propositions-1:
    heading: "Propositions - Draft Draft I"
    summary: "An attempt to create basis vectors"
    date: "15/02/2026"
    careless-wonder: true
    draft: true

